version: '3.7'
#docker compose build --build-arg TAG=1.0 or provide .env file n the directory

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    build:
      context: ./docker-rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 61613:61613
      - 15671:15671
      - 15672:15672
    volumes:
      #- ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      #- ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - rabbitmq_data:/var/log/rabbitmq
    #networks:
      #- rabbitmq_net
    restart: always

volumes:
  rabbitmq_data: